version: "3"

services: 
  clon:
    build: . 
    ports: 
        - 3000:8080
    volumes: 
        - .:/usr/src/app
        - /usr/src/app/.next
        - /usr/src/app/node_modules
    restart: always
